drop database if exists gym;

-- Creo la base de datos
CREATE DATABASE IF NOT EXISTS GYM;
USE GYM;


-- Creacion de tablas de 12 entidades sin FK
CREATE TABLE IF NOT EXISTS USUARIOS(
	Nro_usuario INT PRIMARY KEY AUTO_INCREMENT,
    CI CHAR(8) UNIQUE,
    Nombre VARCHAR(30) NOT NULL,
    Apellido VARCHAR(30) NOT NULL,
    Telefono VARCHAR(30),
    Fecha_nacimiento DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTES(
	Nro_cliente INT PRIMARY KEY,
    Email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS STAFF(
	Nro_staff INT PRIMARY KEY,
    Fecha_contratacion DATE NOT NULL,
    ID_rol INT NOT NULL,
    Nro_local INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Sueldo FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCALES(
	Nro INT AUTO_INCREMENT PRIMARY KEY,
    calle VARCHAR(100) NOT NULL,
    Esquina VARCHAR(100) NOT NULL,
    Numero_puerta VARCHAR(10) NOT NULL,
    Telefono VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS SALAS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100),
    Capacidad INT
);

CREATE TABLE IF NOT EXISTS RUTINAS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    Nombre Varchar(100) NOT NULL,
    Notas MEDIUMTEXT,
    Nro_staff INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EQUIPAMIENTOS(
	Nro INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion MEDIUMTEXT
);

CREATE TABLE IF NOT EXISTS MEMBRESIAS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    Precio FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS PAGOS(
	Nro_ticket INT PRIMARY KEY AUTO_INCREMENT,
    Fecha DATE NOT NULL,
    Hora TIME NOT NULL,
    Monto_Total FLOAT NOT NULL,
    Metodo_Pago INT NOT NULL,
    Nro_cliente INT NOT NULL,
    Nro_local INT NOT NULL
);

CREATE TABLE IF NOT EXISTS METODOS_PAGO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    Nombre_metodo VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS DIAS(
	Nro INT PRIMARY KEY AUTO_INCREMENT,
    Nombre_dia VARCHAR(20) NOT NULL
);


-- Creacion de 12 tablas generadas por relaciones si FK
CREATE TABLE IF NOT EXISTS CLIENTES_RUTINAS(
	ID_cliente_rutina INT PRIMARY KEY AUTO_INCREMENT,
    Nro_cliente INT NOT NULL,
    ID_rutina INT NOT NULL,
    UNIQUE (Nro_cliente, ID_rutina)
);

CREATE TABLE IF NOT EXISTS CLIENTES_MEMBRESIA(
	Nro_cliente INT NOT NULL,
    ID_membresia INT NOT NULL,
    Dias_acceso_disponible INT NOT NULL,
    PRIMARY KEY (Nro_cliente, ID_membresia)
);

CREATE TABLE IF NOT EXISTS EQUIPAMIENTOS_RUTINAS(
	ID_rutina INT NOT NULL,
    Nro_equipamiento INT NOT NULL,
    PRIMARY KEY (ID_rutina, Nro_equipamiento)
);

CREATE TABLE IF NOT EXISTS PAGOS_MEMBRESIA(
	Nro_pago INT NOT NULL,
	ID_membresia INT NOT NULL,
    PRIMARY KEY (Nro_pago, ID_membresia)
);

CREATE TABLE IF NOT EXISTS SALAS_EQUIPAMIENTOS(
	ID_sala INT NOT NULL,
	Nro_equipamiento INT NOT NULL,
    PRIMARY KEY (ID_sala, Nro_equipamiento)
);

CREATE TABLE IF NOT EXISTS SALAS_MEMBRESIAS(
	ID_sala INT NOT NULL,
    ID_membresia INT NOT NULL,
    PRIMARY KEY (ID_sala, ID_membresia)
);

CREATE TABLE IF NOT EXISTS LOCALES_SALAS(
	Nro_local INT NOT NULL,
    ID_sala INT NOT NULL,
    PRIMARY KEY (Nro_local, ID_sala)
);

CREATE TABLE IF NOT EXISTS DIAS_LOCALES(
	Nro_dia INT NOT NULL,
    Nro_local INT NOT NULL,
    Hora_apertura TIME NOT NULL,
    Hora_cierre TIME NOT NULL,
    PRIMARY KEY (Nro_dia, Nro_local)
);

CREATE TABLE IF NOT EXISTS DIAS_CLIENTES_RUTINAS(
	Nro_dia INT NOT NULL,
    ID_cliente_rutina INT NOT NULL,
    PRIMARY KEY (Nro_dia, ID_cliente_rutina)
);

CREATE TABLE IF NOT EXISTS DIAS_TRABAJO_STAFF(
	Nro_dia INT NOT NULL,
    Nro_staff INT NOT NULL,
    Horario_salida TIME NOT NULL,
    Hora_entrada TIME NOT NULL,
    PRIMARY KEY (Nro_dia, Nro_staff)
);

CREATE TABLE IF NOT EXISTS MEMBRESIAS_PERMITEN_LOCALES(
	Nro_local INT NOT NULL,
    ID_membresia INT NOT NULL,
    PRIMARY KEY (Nro_local, ID_membresia)
);

CREATE TABLE IF NOT EXISTS LOCALES_OFRECEN_MEMBRESIAS(
	Nro_local INT NOT NULL,
    ID_membresia INT NOT NULL,
    PRIMARY KEY (Nro_local, ID_membresia)
);


-- Agregarcion de relaciones por FOREIGN KEYS en entidades
ALTER TABLE CLIENTES
ADD CONSTRAINT fk_clientes_usuarios FOREIGN KEY (Nro_cliente) REFERENCES USUARIOS(Nro_usuario) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE STAFF
ADD CONSTRAINT fk_staff_usuarios FOREIGN KEY (Nro_staff) REFERENCES USUARIOS(Nro_usuario) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_staff_roles FOREIGN KEY (ID_rol) REFERENCES ROLES(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_staff_locales FOREIGN KEY (Nro_local) REFERENCES LOCALES(Nro) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE RUTINAS
ADD CONSTRAINT fk_rutinas_staff FOREIGN KEY (Nro_staff) REFERENCES STAFF(Nro_staff) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE PAGOS
ADD CONSTRAINT fk_pagos_locales FOREIGN KEY (Nro_local) REFERENCES LOCALES(Nro) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_pagos_metodo_pago FOREIGN KEY (Metodo_pago) REFERENCES METODOS_PAGO(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_pagos_clientes FOREIGN KEY (Nro_cliente) REFERENCES CLIENTES(Nro_cliente) ON DELETE RESTRICT ON UPDATE CASCADE;

-- Agregarcion de relaciones por FOREIGN KEYS en tablas generadas por relaciones
ALTER TABLE CLIENTES_RUTINAS
ADD CONSTRAINT fk_clientesRutinas_clientes FOREIGN KEY (Nro_cliente) REFERENCES CLIENTES(Nro_cliente) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_clientesRutinas_rutinas FOREIGN KEY (ID_rutina) REFERENCES RUTINAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CLIENTES_MEMBRESIA
ADD CONSTRAINT fk_clientesMembresias_clientes FOREIGN KEY (Nro_cliente) REFERENCES CLIENTES(Nro_cliente) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_clientesMembresias_membresias FOREIGN KEY (ID_membresia) REFERENCES MEMBRESIAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE EQUIPAMIENTOS_RUTINAS
ADD CONSTRAINT fk_equipamientosRutinas_rutinas FOREIGN KEY (ID_rutina) REFERENCES RUTINAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_equipamientosRutinas_equipamientos FOREIGN KEY (Nro_equipamiento) REFERENCES EQUIPAMIENTOS(Nro) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE PAGOS_MEMBRESIA
ADD CONSTRAINT fk_pagosMembresias_pagos FOREIGN KEY (Nro_pago) REFERENCES PAGOS(Nro_ticket) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_pagosMembresias_membresias FOREIGN KEY (ID_membresia) REFERENCES MEMBRESIAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE SALAS_EQUIPAMIENTOS
ADD CONSTRAINT fk_salasEquipamientos_salas FOREIGN KEY (ID_sala) REFERENCES SALAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_salasEquipamientos_equipamientos FOREIGN KEY (Nro_equipamiento) REFERENCES EQUIPAMIENTOS(Nro) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE SALAS_MEMBRESIAS
ADD CONSTRAINT fk_salasMembresias_salas FOREIGN KEY (ID_sala) REFERENCES SALAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_salasMembresias_membresias FOREIGN KEY (ID_membresia) REFERENCES MEMBRESIAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE LOCALES_SALAS
ADD CONSTRAINT fk_localesSalas_salas FOREIGN KEY (ID_sala) REFERENCES SALAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_localesSalas_locales FOREIGN KEY (Nro_local) REFERENCES LOCALES(Nro) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE DIAS_LOCALES
ADD CONSTRAINT fk_diasLocales_dias FOREIGN KEY (Nro_dia) REFERENCES DIAS(Nro) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_diasLocales_locales FOREIGN KEY (Nro_local) REFERENCES LOCALES(Nro) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE DIAS_CLIENTES_RUTINAS
ADD CONSTRAINT fk_diasClientesRutinas_dias FOREIGN KEY (Nro_dia) REFERENCES DIAS(Nro) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_diasClientesRutinas_clientesRutinas FOREIGN KEY (ID_cliente_rutina) REFERENCES CLIENTES_RUTINAS(ID_cliente_rutina) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE DIAS_TRABAJO_STAFF
ADD CONSTRAINT fk_diasTrabajoStaff_dias FOREIGN KEY (Nro_dia) REFERENCES DIAS(Nro) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_diasTrabajoStaff_staff FOREIGN KEY (Nro_staff) REFERENCES STAFF(Nro_staff) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE MEMBRESIAS_PERMITEN_LOCALES
ADD CONSTRAINT fk_membresiasPermitenLocales_locales FOREIGN KEY (Nro_local) REFERENCES LOCALES(Nro) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_membresiasPermitenLocales_membresias FOREIGN KEY (ID_membresia) REFERENCES MEMBRESIAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE LOCALES_OFRECEN_MEMBRESIAS
ADD CONSTRAINT fk_localesOfresenMembresias_locales FOREIGN KEY (Nro_local) REFERENCES LOCALES(Nro) ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT fk_localesOfresenMembresias_membresias FOREIGN KEY (ID_membresia) REFERENCES MEMBRESIAS(ID) ON DELETE RESTRICT ON UPDATE CASCADE;
